# Creating, Planting, and Finding Signals Within Noise
Elizabeth Kapelevich

In [1]:
import math
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt
import signals_and_noise as san

In [2]:
Time1, Position1 = np.loadtxt("mock_data_challenge_1.dat").T
Time2, Position2 = np.loadtxt("mock_data_challenge_2.dat").T

In [3]:
# %%timeit
# san.fs_search(0.012, 2, 20, [Time1, Position1], 1.5, 8, 0.012, 2.0, 20, 10, 2.0, 10, 5.0)

In [4]:
# %%timeit
# san.fs_search(0.012, 2, 20, [Time2, Position2], 0.5, 4, 0.012, 2.0, 20, 0.5, 2.0, 10, 0.5)

## Main Goal for Week of 6/27:
Adjust the `template`, `integrator`, `cross_correlation`, and `fs_search` functions to take a frequency array as input and output the proper result.
#### Tasks:
* Within the `template` function, create a meshgrid that will allow many different values of frequencies that can be used by many different values of the `S` equation. $\checkmark$
* Using a for-loop, evaluate ` S ` over values of ` frequency ` and ` time_stamps ` so that the output is an array of ` S ` values. $\checkmark$
* Once that is complete, go through the ` integrator ` function and the ` cross_correlation ` function and update the code so that the frequency parameter can be properly passed as an array and calculated.
* Note: Adjusting/creating for-loops and meshgrids may help.

In [5]:
def cross_correlation(del_T_0, t_start, t_max, data_time_series, a, f, sigma, t_duration, del_T):

    C = []                                         # initializing the value of the variable
    time_stamps = []                               # creating empty list to save values for plotting

    t_stamps, frequency = np.meshgrid(time_stamps, f)

    while t_start <= t_max:
        time_stamps.append(t_start)
        
        integ = san.integrator(data_time_series, a, f, sigma, t_start, t_duration, del_T)
        C.append(integ)                            # computing integral over all 'sections'
        
        t_start += del_T_0                         # moving intial time of template over increments of del_T
        
    return time_stamps, C                          # returning the list of integration results

In [6]:
a = 1.5
f = np.array([1, 2, 3])
sigma = 0.1
t_start = 2
t_duration = 8
t_max = 20
data_time_series = [Time1, Position1]
del_T_0 = 0.012
del_T = 0.012

In [7]:
my_crosscorr = cross_correlation(del_T_0, t_start, t_max, data_time_series, a, f, sigma, t_duration, del_T)

In [8]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40])

In [9]:
A, B = np.meshgrid(a, b)
print(A)
print(B)
print(A*B)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[10 10 10 10 10]
 [20 20 20 20 20]
 [30 30 30 30 30]
 [40 40 40 40 40]]
[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
