# Creating, Planting, and Finding Signals Within Noise
Elizabeth Kapelevich

In [1]:
import math
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt
import signals_and_noise as san

In [2]:
Time1, Position1 = np.loadtxt("mock_data_challenge_1.dat").T
Time2, Position2 = np.loadtxt("mock_data_challenge_2.dat").T

In [ ]:
%%timeit
san.fs_search(0.012, 2, 20, [Time1, Position1], 1.5, 8, 0.012, 2.0, 20, 10, 2.0, 10, 5.0)

In [ ]:
san.fs_search(0.012, 2, 20, [Time2, Position2], 0.5, 4, 0.012, 2.0, 20, 0.5, 2.0, 10, 0.5)

In [ ]:
def template(A, f, sigma, t_0, t_duration, data_time_stamps, ad_hoc_grid = 10000):
    
    del_T_data = np.diff(data_time_stamps)[0]
    t_end = t_duration + t_0
    time_stamps = np.linspace(t_0, t_end + del_T_data, ad_hoc_grid)
    
    t_mean = np.mean(time_stamps)
    S = A*np.sin(2*np.pi*f*time_stamps)*np.exp((-(time_stamps - t_mean)**2)/(2*sigma))
 
    s = interpolate.interp1d(time_stamps, S)
    Template = s(data_time_stamps[(data_time_stamps >= t_0)*(data_time_stamps <= t_end)])
    
    template_series = np.zeros_like(data_time_stamps)
    
    index_prefix = template_series[data_time_stamps < t_0]
    index_suffix = template_series[data_time_stamps > t_end]
    
    closest_to_t0 = data_time_stamps[np.argmin(np.abs(t_0 - data_time_stamps))]
    closest_to_tend = data_time_stamps[np.argmin(np.abs(t_end - data_time_stamps))]
    
    return np.hstack((index_prefix, Template, index_suffix))

### Meshgrid Assignment:

Meshgrid creates matrices that have proportionate sizes.
* Within the `template` function, create a meshgrid that will allow many different values of frequencies that can be multiplied with many different values of the `S` equation.
* Try printing the multiplied values to make sure it is being calculated properly. Once it works, include sigma within the calculation so those values are also multiplied with different values from the `S` equation.

In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

In [7]:
A, B = np.meshgrid(a, b)
print(A*B)

[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]
 [ 50 100 150 200 250]]
