# Creating, Planting, and Finding Signals Within Noise
Elizabeth Kapelevich

In [1]:
import time
import math
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt
import signals_and_noise as san

In [2]:
Time1, Position1 = np.loadtxt("mock_data_challenge_1.dat").T
Time2, Position2 = np.loadtxt("mock_data_challenge_2.dat").T

## Main Goal for Week of 7/04:
* Begin PyCBC and learn implementation
### Mini-goal:
* Adjust the `frequency_time_search` function to allow $\sigma$ (standard deviation) as an array and output the corresponding value that relates to the cross-correlation and frequency.

In [117]:
def frequency_time_sigma_search(del_T_0, t_start, t_max, data_time_series, a, f, sigma, t_duration, del_T):
    
    time_values = []
    C_values = []
    
    for i in sigma:
        times, C = san.cross_correlation(del_T_0, t_start, t_max, data_time_series, a, f, i, t_duration, del_T)
        time_values.append(times)
        C_values.append(C)

    C = np.array(C)                                        # creating an array from a list
    C_values = np.array(C_values)
    
    # shape of C_values is: sigma, C, frequency
    
    C_max_value = np.max(C)                                # finding the maximum value
    find_index = np.where(C_max_value == C)                # finding index of maximum value
    # need to figure out a way to 
    index_row = int(find_index[0])                         # finding row of the index
    index_column = int(find_index[1])                      # finding column of the index
    
    time_correct = times[index_row]                        # value of time from row index
    frequency_correct = f[index_column]                    # value of frequency from column index
#    sigma_correct = sigma_values[f]
    
    return time_correct, frequency_correct #, sigma_correct

In [118]:
a = 1.5
f = np.linspace(0, 2, 1)
sigma = np.linspace(0, 1, 1)
t_0 = 2.01
t_start = 2
t_duration = 8
t_max = 20
data_time_series = [Time1, Position1]
data_time_stamps = Time1
del_T_0 = 0.012
del_T = 0.012

In [119]:
search = frequency_time_sigma_search(del_T_0, t_start, t_max, data_time_series, a, f, sigma, t_duration, del_T)

TypeError: tuple indices must be integers or slices, not tuple

In [33]:
search

(4.0280000000000005, 6.842105263157895)

In [76]:
array = np.array([[[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]], 
                  
                  [[10, 11, 12], 
                   [13, 14, 15], 
                   [16, 17, 18]]])

In [123]:
print("first entire array: ")
print()
print(array[0])
print()
print("first row in each array: ")
print()
print(array [:,0])
print()
print("first column in each array: ")
print()
print(array[:,:,0])

x = np.max(array)                                # finding the maximum value
find_index = np.where(x == array)
index_row = int(find_index[0])                         # finding row of the index
index_column = int(find_index[1])
print(index_row)
print(index_column)

first entire array: 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

first row in each array: 

[[ 1  2  3]
 [10 11 12]]

first column in each array: 

[[ 1  4  7]
 [10 13 16]]
1
2


https://stackoverflow.com/questions/19770361/find-index-positions-where-3d-array-meets-multiple-conditions

Use above link to figure out how to find position of max value in 3D array using `np.where()`